Token object
CSCI3100-B5/Classroom-Interchat pull request #60
Opened 2021-04-10 08:55 UTC by Jimmy618

Not ready for merging

2021-04-10 09:08 UTC, Henry-YSLin requested changes

2021-04-10 09:08 UTC, Henry-YSLin commented on src/server/token/token.controller.js
> +    });
If you are awaiting the operation, you don't need to use `then`. 

Use it like this:
```js
const list = await Token.find({ receivedBy: user.id }).exec();
// Then write code to read the list
```

2021-04-10 09:08 UTC, Henry-YSLin commented on src/server/token/token.controller.js
> +        });
No need to write out all the properties. 

1. Populate `createdBy` and `receivedBy` when you query the database
```js
const list = await Token.find({ receivedBy: user.id }).populate('createdBy').populate('receivedBy').exec();
```

2. Get all the properties by using `filterSafe`
```js
list.map(x => x.filterSafe())
```

2021-04-10 15:43 UTC, Jimmy618 commented
404 not found, for some reason

2021-04-11 06:20 UTC, Henry-YSLin approved these changes

2021-04-11 06:20 UTC, merged